(deftheme zenburn
  "Created 2015-06-29.")

(custom-theme-set-variables
 'zenburn
 '(ansi-color-names-vector ["#3F3F3F" "#CC9393" "#7F9F7F" "#F0DFAF" "#8CD0D3" "#DC8CC3" "#93E0E3" "#DCDCCC"]))

(custom-theme-set-faces
 'zenburn
 '(button ((t (:underline t))))
 '(link ((t (:foreground "#F0DFAF" :underline t :weight bold))))
 '(link-visited ((t (:foreground "#D0BF8F" :underline t :weight normal))))
 '(cursor ((t (:foreground "#DCDCCC" :background "#FFFFEF"))))
 '(escape-glyph ((t (:foreground "#F0DFAF" :bold t))))
 '(fringe ((t (:foreground "#DCDCCC" :background "#4F4F4F"))))
 '(header-line ((t (:foreground "#F0DFAF" :background "#2B2B2B" :box (:line-width -1 :style released-button)))))
 '(highlight ((t (:background "#383838"))))
 '(success ((t (:foreground "#7F9F7F" :weight bold))))
 '(warning ((t (:foreground "#DFAF8F" :weight bold))))
 '(tooltip ((t (:foreground "#DCDCCC" :background "#4F4F4F"))))
 '(compilation-info ((t (:foreground "#BFEBBF" :underline t))))
 '(compilation-line-number ((t (:foreground "#F0DFAF"))))
 '(compilation-mode-line-exit ((t (:foreground "#9FC59F" :weight bold))))
 '(compilation-mode-line-fail ((t (:foreground "#CC9393" :weight bold))))
 '(compilation-mode-line-run ((t (:foreground "#F0DFAF" :weight bold))))
 '(completions-annotations ((t (:foreground "#656555"))))
 '(match ((t (:background "#2B2B2B" :foreground "#DFAF8F" :weight bold))))
 '(isearch ((t (:foreground "#D0BF8F" :weight bold :background "#5F5F5F"))))
 '(isearch-fail ((t (:foreground "#DCDCCC" :background "#8C5353"))))
 '(lazy-highlight ((t (:foreground "#D0BF8F" :weight bold :background "#383838"))))
 '(menu ((t (:foreground "#DCDCCC" :background "#3F3F3F"))))
 '(minibuffer-prompt ((t (:foreground "#F0DFAF"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#8FB28F" :background "#2B2B2B" :box (:line-width -1 :style released-button))) (t :inverse-video t)))
 '(mode-line-buffer-id ((t (:foreground "#F0DFAF" :weight bold))))
 '(mode-line-inactive ((t (:foreground "#5F7F5F" :background "#383838" :box (:line-width -1 :style released-button)))))
 '(region ((((class color) (min-colors 89)) (:background "#2B2B2B")) (t :inverse-video t)))
 '(secondary-selection ((t (:background "#5F5F5F"))))
 '(trailing-whitespace ((t (:background "#CC9393"))))
 '(vertical-border ((t (:foreground "#DCDCCC"))))
 '(font-lock-builtin-face ((t (:foreground "#DCDCCC" :weight bold))))
 '(font-lock-comment-face ((t (:foreground "#7F9F7F"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#5F7F5F"))))
 '(font-lock-constant-face ((t (:foreground "#BFEBBF"))))
 '(font-lock-doc-face ((t (:foreground "#9FC59F"))))
 '(font-lock-function-name-face ((t (:foreground "#93E0E3"))))
 '(font-lock-keyword-face ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#94BFF3"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#7F9F7F" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#CC9393"))))
 '(font-lock-type-face ((t (:foreground "#7CB8BB"))))
 '(font-lock-variable-name-face ((t (:foreground "#DFAF8F"))))
 '(font-lock-warning-face ((t (:foreground "#D0BF8F" :weight bold))))
 '(ac-candidate-face ((t (:background "#6F6F6F" :foreground "#000000"))))
 '(ac-selection-face ((t (:background "#4C7073" :foreground "#DCDCCC"))))
 '(popup-tip-face ((t (:background "#D0BF8F" :foreground "#000000"))))
 '(popup-scroll-bar-foreground-face ((t (:background "#366060"))))
 '(popup-scroll-bar-background-face ((t (:background "#2B2B2B"))))
 '(popup-isearch-match ((t (:background "#3F3F3F" :foreground "#DCDCCC"))))
 '(flymake-errline ((((supports :underline (:style wave))) (:underline (:style wave :color "#CC9393") :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground "#BC8383" :weight bold :underline t))))
 '(flymake-warnline ((((supports :underline (:style wave))) (:underline (:style wave :color "#DFAF8F") :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground "#DFAF8F" :weight bold :underline t))))
 '(flyspell-duplicate ((((supports :underline (:style wave))) (:underline (:style wave :color "#DFAF8F") :inherit unspecified)) (t (:foreground "#DFAF8F" :weight bold :underline t))))
 '(flyspell-incorrect ((((supports :underline (:style wave))) (:underline (:style wave :color "#CC9393") :inherit unspecified)) (t (:foreground "#BC8383" :weight bold :underline t))))
 '(message-cited-text ((t (:inherit font-lock-comment-face))))
 '(message-header-name ((t (:foreground "#8FB28F"))))
 '(message-header-other ((t (:foreground "#7F9F7F"))))
 '(message-header-to ((t (:foreground "#F0DFAF" :weight bold))))
 '(message-header-cc ((t (:foreground "#F0DFAF" :weight bold))))
 '(message-header-newsgroups ((t (:foreground "#F0DFAF" :weight bold))))
 '(message-header-subject ((t (:foreground "#DFAF8F" :weight bold))))
 '(message-header-xheader ((t (:foreground "#7F9F7F"))))
 '(message-mml ((t (:foreground "#F0DFAF" :weight bold))))
 '(message-separator ((t (:inherit font-lock-comment-face))))
 '(org-agenda-date-today ((t (:foreground "#FFFFEF" :slant italic :weight bold))))
 '(org-agenda-structure ((t (:inherit font-lock-comment-face))))
 '(org-archived ((t (:foreground "#DCDCCC" :weight bold))))
 '(org-checkbox ((t (:background "#5F5F5F" :foreground "#FFFFEF" :box (:line-width 1 :style released-button)))))
 '(org-date ((t (:foreground "#8CD0D3" :underline t))))
 '(org-done ((t (:bold t :weight bold :foreground "#AFD8AF"))))
 '(org-formula ((t (:foreground "#D0BF8F"))))
 '(org-headline-done ((t (:foreground "#AFD8AF"))))
 '(org-hide ((t (:foreground "#2B2B2B"))))
 '(org-level-1 ((t (:foreground "#DFAF8F"))))
 '(org-level-2 ((t (:foreground "#BFEBBF"))))
 '(org-level-3 ((t (:foreground "#7CB8BB"))))
 '(org-level-4 ((t (:foreground "#D0BF8F"))))
 '(org-level-5 ((t (:foreground "#93E0E3"))))
 '(org-level-6 ((t (:foreground "#9FC59F"))))
 '(org-level-7 ((t (:foreground "#8C5353"))))
 '(org-level-8 ((t (:foreground "#4C7073"))))
 '(org-link ((t (:foreground "#D0BF8F" :underline t))))
 '(org-scheduled ((t (:foreground "#BFEBBF"))))
 '(org-scheduled-previously ((t (:foreground "#CC9393"))))
 '(org-scheduled-today ((t (:foreground "#94BFF3"))))
 '(org-sexp-date ((t (:foreground "#94BFF3" :underline t))))
 '(org-special-keyword ((t (:inherit font-lock-comment-face))))
 '(org-table ((t (:foreground "#9FC59F"))))
 '(org-tag ((t (:bold t :weight bold))))
 '(org-time-grid ((t (:foreground "#DFAF8F"))))
 '(org-todo ((t (:bold t :foreground "#CC9393" :weight bold))))
 '(org-upcoming-deadline ((t (:inherit font-lock-keyword-face))))
 '(org-warning ((t (:bold t :foreground "#CC9393" :weight bold :underline nil))))
 '(org-column ((t (:background "#2B2B2B"))))
 '(org-column-title ((t (:background "#2B2B2B" :underline t :weight bold))))
 '(org-mode-line-clock ((t (:foreground "#DCDCCC" :background "#2B2B2B"))))
 '(org-mode-line-clock-overrun ((t (:foreground "#3F3F3F" :background "#BC8383"))))
 '(org-ellipsis ((t (:foreground "#E0CF9F" :underline t))))
 '(org-footnote ((t (:foreground "#93E0E3" :underline t))))
 '(outline-1 ((t (:foreground "#DFAF8F"))))
 '(outline-2 ((t (:foreground "#BFEBBF"))))
 '(outline-3 ((t (:foreground "#7CB8BB"))))
 '(outline-4 ((t (:foreground "#D0BF8F"))))
 '(outline-5 ((t (:foreground "#93E0E3"))))
 '(outline-6 ((t (:foreground "#9FC59F"))))
 '(outline-7 ((t (:foreground "#8C5353"))))
 '(outline-8 ((t (:foreground "#4C7073"))))
 '(show-paren-mismatch ((t (:foreground "#DCA3A3" :background "#6F6F6F" :weight bold))))
 '(show-paren-match ((t (:background "#6F6F6F" :weight bold))))
 '(sp-show-pair-mismatch-face ((t (:foreground "#DCA3A3" :background "#6F6F6F" :weight bold))))
 '(sp-show-pair-match-face ((t (:background "#6F6F6F" :weight bold))))
 '(speedbar-button-face ((t (:foreground "#9FC59F"))))
 '(speedbar-directory-face ((t (:foreground "#93E0E3"))))
 '(speedbar-file-face ((t (:foreground "#DCDCCC"))))
 '(speedbar-highlight-face ((t (:foreground "#3F3F3F" :background "#9FC59F"))))
 '(speedbar-selected-face ((t (:foreground "#CC9393"))))
 '(speedbar-separator-face ((t (:foreground "#3F3F3F" :background "#7CB8BB"))))
 '(speedbar-tag-face ((t (:foreground "#F0DFAF"))))
 '(web-mode-builtin-face ((t (:inherit font-lock-builtin-face))))
 '(web-mode-comment-face ((t (:inherit font-lock-comment-face))))
 '(web-mode-constant-face ((t (:inherit font-lock-constant-face))))
 '(web-mode-css-at-rule-face ((t (:foreground "#DFAF8F"))))
 '(web-mode-css-pseudo-class-face ((t (:foreground "#AFD8AF" :weight bold))))
 '(web-mode-doctype-face ((t (:inherit font-lock-comment-face))))
 '(web-mode-folded-face ((t (:underline t))))
 '(web-mode-function-name-face ((t (:foreground "#8CD0D3"))))
 '(web-mode-html-attr-name-face ((t (:foreground "#DFAF8F"))))
 '(web-mode-html-attr-value-face ((t (:inherit font-lock-string-face))))
 '(web-mode-html-tag-face ((t (:foreground "#93E0E3"))))
 '(web-mode-keyword-face ((t (:inherit font-lock-keyword-face))))
 '(web-mode-preprocessor-face ((t (:inherit font-lock-preprocessor-face))))
 '(web-mode-string-face ((t (:inherit font-lock-string-face))))
 '(web-mode-type-face ((t (:inherit font-lock-type-face))))
 '(web-mode-variable-name-face ((t (:inherit font-lock-variable-name-face))))
 '(web-mode-symbol-face ((t (:inherit font-lock-constant-face))))
 '(web-mode-warning-face ((t (:inherit font-lock-warning-face))))
 '(default ((t (:foreground "#DCDCCC" :background "#3F3F3F")))))

(provide-theme 'zenburn)
